- name: Create secret
  k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: aws-route53-secret
      type: Opaque
      data:
        AWS_ACCESS_KEY_ID: QUtJQTRINjMzXXXXXXXXTDdZTlA=
        AWS_SECRET_ACCESS_KEY: T1J0bXXXXXXXXVpDb0hET0J2MkVlclhTZ01kdVl5Q3NYc2x0a0R2Yw==
